# This is Honeybadger experimenting with Backstage TechDocs for the dev portal.
#
# See https://www.mkdocs.org/user-guide/configuration/ for available options
# in MkDocs and https://backstage.io/docs/features/techdocs/creating-and-publishing
# for context regarding Backstage TechDocs.

# Required docs title
site_name: backstage-techdocs-example documentation

#docs_dir: docs/
nav:
  - Home: index.md
  - other-page.md

edit_uri: edit/main/docs/
